name: Test Kubernetes Deployment with KinD

on:
  push:
    branches:
      - main

jobs:
  test-k8s:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up KinD cluster
        uses: helm/kind-action@v1.8.0

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f ./deployment.yaml
          kubectl get pods
