name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - Dev
      - staging

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

  unit-test:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm run test

  docker-deploy:
    needs: unit-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Environment Variables Based on Branch
        run: |
          echo "Current branch: $GITHUB_REF_NAME"
          if [[ "$GITHUB_REF_NAME" == "Dev" ]]; then
            echo "CI_ENVIRONMENT_NAME=dev" >> $GITHUB_ENV
            echo "AWS_ECR_REPOSITORY_NAME=dev" >> $GITHUB_ENV
          elif [[ "$GITHUB_REF_NAME" == "staging" ]]; then
            echo "CI_ENVIRONMENT_NAME=staging" >> $GITHUB_ENV
            echo "AWS_ECR_REPOSITORY_NAME=staging" >> $GITHUB_ENV
          else
            echo "CI_ENVIRONMENT_NAME=default" >> $GITHUB_ENV
            echo "AWS_ECR_REPOSITORY_NAME=node.js" >> $GITHUB_ENV
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Automatic Tagging of Releases
        id: increment-git-tag
        run: |
          if [ -f ./build/git_update.sh ]; then
            chmod +x ./build/git_update.sh
            ./build/git_update.sh -v major
          else
            echo "⚠️ Warning: ./build/git_update.sh not found. Skipping tagging."
          fi

      - name: Build, Tag, and Push the Image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: latest
        run: |
          echo "Using ECR repo: $AWS_ECR_REPOSITORY_NAME"
          IMAGE_URI="$ECR_REGISTRY/$AWS_ECR_REPOSITORY_NAME:$IMAGE_TAG"
          echo "Building Docker image: $IMAGE_URI"
          docker build -t "$IMAGE_URI" .
          docker push "$IMAGE_URI"
